/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as loanPoolSol from './LoanPool.sol/index.js';
export type { loanPoolSol };
export type { KYCRegistry } from './KYCRegistry.js';
export type { LoanFactory } from './LoanFactory.js';
export type { ReputationRegistry } from './ReputationRegistry.js';
export * as factories from './factories/index.js';
export { KYCRegistry__factory } from './factories/KYCRegistry__factory.js';
export { LoanFactory__factory } from './factories/LoanFactory__factory.js';
export type { IKYCRegistry } from './LoanPool.sol/IKYCRegistry.js';
export { IKYCRegistry__factory } from './factories/LoanPool.sol/IKYCRegistry__factory.js';
export type { IReputationRegistry } from './LoanPool.sol/IReputationRegistry.js';
export { IReputationRegistry__factory } from './factories/LoanPool.sol/IReputationRegistry__factory.js';
export type { LoanPool } from './LoanPool.sol/LoanPool.js';
export { LoanPool__factory } from './factories/LoanPool.sol/LoanPool__factory.js';
export { ReputationRegistry__factory } from './factories/ReputationRegistry__factory.js';