/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKYCRegistry, IKYCRegistryInterface } from "../../LoanPool.sol/IKYCRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "isVerified",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IKYCRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IKYCRegistryInterface {
      return new Interface(_abi) as IKYCRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKYCRegistry {
      return new Contract(address, _abi, runner) as unknown as IKYCRegistry;
    }
  }
  