/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKYCRegistry__factory } from './IKYCRegistry__factory.js';
export { IReputationRegistry__factory } from './IReputationRegistry__factory.js';
export { LoanPool__factory } from './LoanPool__factory.js';