/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReputationRegistry, IReputationRegistryInterface } from "../../LoanPool.sol/IReputationRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "successful",
        "type": "bool"
      }
    ],
    "name": "recordOutcome",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IReputationRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IReputationRegistryInterface {
      return new Interface(_abi) as IReputationRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReputationRegistry {
      return new Contract(address, _abi, runner) as unknown as IReputationRegistry;
    }
  }
  