/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKYCRegistry } from './IKYCRegistry.js';
export type { IReputationRegistry } from './IReputationRegistry.js';
export type { LoanPool } from './LoanPool.js';