/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LoanPoolInterface extends Interface {
    getFunction(nameOrSignature: "approvedMerchant" | "approvedMerchants" | "aprBps" | "borrower" | "cancelUnfunded" | "claimFundingRefund" | "claimRepayment" | "claimed" | "contribute" | "contributed" | "createdAt" | "defaultQuorumBps" | "defaultVoteWeight" | "durationSeconds" | "factory" | "getApprovedMerchants" | "getLenderInfo" | "getSummary" | "hasDefaultVoted" | "kycRegistry" | "maturity" | "maxSpendWei" | "refunded" | "repay" | "reputationRegistry" | "spend" | "status" | "targetWei" | "totalContributed" | "totalRepaid" | "totalRepayable" | "totalSpent" | "voteDefault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DefaultVoteCast" | "Funded" | "FundingCancelled" | "FundingRefunded" | "LoanActivated" | "LoanDefaulted" | "LoanPoolCreated" | "LoanRepaid" | "RepaymentClaimed" | "RepaymentReceived" | "SpendExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'approvedMerchant', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'approvedMerchants', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'aprBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'borrower', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelUnfunded', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimFundingRefund', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimRepayment', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'contribute', values?: undefined): string;
encodeFunctionData(functionFragment: 'contributed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'createdAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'defaultQuorumBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'defaultVoteWeight', values?: undefined): string;
encodeFunctionData(functionFragment: 'durationSeconds', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getApprovedMerchants', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLenderInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSummary', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasDefaultVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'kycRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'maturity', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxSpendWei', values?: undefined): string;
encodeFunctionData(functionFragment: 'refunded', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'repay', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputationRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'spend', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'status', values?: undefined): string;
encodeFunctionData(functionFragment: 'targetWei', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalContributed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRepaid', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRepayable', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSpent', values?: undefined): string;
encodeFunctionData(functionFragment: 'voteDefault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'approvedMerchant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approvedMerchants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'aprBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'borrower', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelUnfunded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimFundingRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRepayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createdAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'defaultQuorumBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'defaultVoteWeight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'durationSeconds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getApprovedMerchants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLenderInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSummary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasDefaultVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kycRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maturity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxSpendWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refunded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'spend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'targetWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalContributed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRepaid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRepayable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSpent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteDefault', data: BytesLike): Result;
  }

  
    export namespace DefaultVoteCastEvent {
      export type InputTuple = [lender: AddressLike, weight: BigNumberish, totalVoteWeight: BigNumberish];
      export type OutputTuple = [lender: string, weight: bigint, totalVoteWeight: bigint];
      export interface OutputObject {lender: string, weight: bigint, totalVoteWeight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundedEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish, totalContributed: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint, totalContributed: bigint];
      export interface OutputObject {lender: string, amount: bigint, totalContributed: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundingCancelledEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundingRefundedEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint];
      export interface OutputObject {lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanActivatedEvent {
      export type InputTuple = [timestamp: BigNumberish];
      export type OutputTuple = [timestamp: bigint];
      export interface OutputObject {timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanDefaultedEvent {
      export type InputTuple = [totalVoteWeight: BigNumberish];
      export type OutputTuple = [totalVoteWeight: bigint];
      export interface OutputObject {totalVoteWeight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanPoolCreatedEvent {
      export type InputTuple = [borrower: AddressLike, targetWei: BigNumberish, maturity: BigNumberish, aprBps: BigNumberish];
      export type OutputTuple = [borrower: string, targetWei: bigint, maturity: bigint, aprBps: bigint];
      export interface OutputObject {borrower: string, targetWei: bigint, maturity: bigint, aprBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [totalRepaid: BigNumberish];
      export type OutputTuple = [totalRepaid: bigint];
      export interface OutputObject {totalRepaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepaymentClaimedEvent {
      export type InputTuple = [lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [lender: string, amount: bigint];
      export interface OutputObject {lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepaymentReceivedEvent {
      export type InputTuple = [borrower: AddressLike, amount: BigNumberish, totalRepaid: BigNumberish];
      export type OutputTuple = [borrower: string, amount: bigint, totalRepaid: bigint];
      export interface OutputObject {borrower: string, amount: bigint, totalRepaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SpendExecutedEvent {
      export type InputTuple = [merchant: AddressLike, amount: BigNumberish, category: BytesLike];
      export type OutputTuple = [merchant: string, amount: bigint, category: string];
      export interface OutputObject {merchant: string, amount: bigint, category: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LoanPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): LoanPool;
    waitForDeployment(): Promise<this>;

    interface: LoanPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approvedMerchant: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    approvedMerchants: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    aprBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    borrower: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelUnfunded: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimFundingRefund: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    claimRepayment: TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    contribute: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    contributed: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createdAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    defaultQuorumBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    defaultVoteWeight: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    durationSeconds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getApprovedMerchants: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getLenderInfo: TypedContractMethod<
      [lender: AddressLike, ],
      [[bigint, bigint, boolean] & {amount: bigint, claimable: bigint, voted: boolean }],
      'view'
    >
    

    
    getSummary: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {_status: bigint, _targetWei: bigint, _totalContributed: bigint, _totalRepaid: bigint, _totalRepayable: bigint, _totalSpent: bigint, _maturity: bigint, _defaultVoteWeight: bigint, _defaultThreshold: bigint }],
      'view'
    >
    

    
    hasDefaultVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    kycRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    maturity: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxSpendWei: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    refunded: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    repay: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    reputationRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    spend: TypedContractMethod<
      [merchant: AddressLike, amount: BigNumberish, category: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    status: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    targetWei: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalContributed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRepaid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRepayable: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSpent: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    voteDefault: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approvedMerchant'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'approvedMerchants'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'aprBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'borrower'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelUnfunded'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimFundingRefund'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimRepayment'): TypedContractMethod<
      [],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createdAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'defaultQuorumBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'defaultVoteWeight'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'durationSeconds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getApprovedMerchants'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLenderInfo'): TypedContractMethod<
      [lender: AddressLike, ],
      [[bigint, bigint, boolean] & {amount: bigint, claimable: bigint, voted: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getSummary'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {_status: bigint, _targetWei: bigint, _totalContributed: bigint, _totalRepaid: bigint, _totalRepayable: bigint, _totalSpent: bigint, _maturity: bigint, _defaultVoteWeight: bigint, _defaultThreshold: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'hasDefaultVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kycRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'maturity'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxSpendWei'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'refunded'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'repay'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'reputationRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'spend'): TypedContractMethod<
      [merchant: AddressLike, amount: BigNumberish, category: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'targetWei'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalContributed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRepaid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRepayable'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSpent'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'voteDefault'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DefaultVoteCast'): TypedContractEvent<DefaultVoteCastEvent.InputTuple, DefaultVoteCastEvent.OutputTuple, DefaultVoteCastEvent.OutputObject>;
getEvent(key: 'Funded'): TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
getEvent(key: 'FundingCancelled'): TypedContractEvent<FundingCancelledEvent.InputTuple, FundingCancelledEvent.OutputTuple, FundingCancelledEvent.OutputObject>;
getEvent(key: 'FundingRefunded'): TypedContractEvent<FundingRefundedEvent.InputTuple, FundingRefundedEvent.OutputTuple, FundingRefundedEvent.OutputObject>;
getEvent(key: 'LoanActivated'): TypedContractEvent<LoanActivatedEvent.InputTuple, LoanActivatedEvent.OutputTuple, LoanActivatedEvent.OutputObject>;
getEvent(key: 'LoanDefaulted'): TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
getEvent(key: 'LoanPoolCreated'): TypedContractEvent<LoanPoolCreatedEvent.InputTuple, LoanPoolCreatedEvent.OutputTuple, LoanPoolCreatedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
getEvent(key: 'RepaymentClaimed'): TypedContractEvent<RepaymentClaimedEvent.InputTuple, RepaymentClaimedEvent.OutputTuple, RepaymentClaimedEvent.OutputObject>;
getEvent(key: 'RepaymentReceived'): TypedContractEvent<RepaymentReceivedEvent.InputTuple, RepaymentReceivedEvent.OutputTuple, RepaymentReceivedEvent.OutputObject>;
getEvent(key: 'SpendExecuted'): TypedContractEvent<SpendExecutedEvent.InputTuple, SpendExecutedEvent.OutputTuple, SpendExecutedEvent.OutputObject>;

    filters: {
      
      'DefaultVoteCast(address,uint256,uint256)': TypedContractEvent<DefaultVoteCastEvent.InputTuple, DefaultVoteCastEvent.OutputTuple, DefaultVoteCastEvent.OutputObject>;
      DefaultVoteCast: TypedContractEvent<DefaultVoteCastEvent.InputTuple, DefaultVoteCastEvent.OutputTuple, DefaultVoteCastEvent.OutputObject>;
    

      'Funded(address,uint256,uint256)': TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
      Funded: TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
    

      'FundingCancelled(uint256)': TypedContractEvent<FundingCancelledEvent.InputTuple, FundingCancelledEvent.OutputTuple, FundingCancelledEvent.OutputObject>;
      FundingCancelled: TypedContractEvent<FundingCancelledEvent.InputTuple, FundingCancelledEvent.OutputTuple, FundingCancelledEvent.OutputObject>;
    

      'FundingRefunded(address,uint256)': TypedContractEvent<FundingRefundedEvent.InputTuple, FundingRefundedEvent.OutputTuple, FundingRefundedEvent.OutputObject>;
      FundingRefunded: TypedContractEvent<FundingRefundedEvent.InputTuple, FundingRefundedEvent.OutputTuple, FundingRefundedEvent.OutputObject>;
    

      'LoanActivated(uint256)': TypedContractEvent<LoanActivatedEvent.InputTuple, LoanActivatedEvent.OutputTuple, LoanActivatedEvent.OutputObject>;
      LoanActivated: TypedContractEvent<LoanActivatedEvent.InputTuple, LoanActivatedEvent.OutputTuple, LoanActivatedEvent.OutputObject>;
    

      'LoanDefaulted(uint256)': TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
      LoanDefaulted: TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
    

      'LoanPoolCreated(address,uint256,uint256,uint256)': TypedContractEvent<LoanPoolCreatedEvent.InputTuple, LoanPoolCreatedEvent.OutputTuple, LoanPoolCreatedEvent.OutputObject>;
      LoanPoolCreated: TypedContractEvent<LoanPoolCreatedEvent.InputTuple, LoanPoolCreatedEvent.OutputTuple, LoanPoolCreatedEvent.OutputObject>;
    

      'LoanRepaid(uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    

      'RepaymentClaimed(address,uint256)': TypedContractEvent<RepaymentClaimedEvent.InputTuple, RepaymentClaimedEvent.OutputTuple, RepaymentClaimedEvent.OutputObject>;
      RepaymentClaimed: TypedContractEvent<RepaymentClaimedEvent.InputTuple, RepaymentClaimedEvent.OutputTuple, RepaymentClaimedEvent.OutputObject>;
    

      'RepaymentReceived(address,uint256,uint256)': TypedContractEvent<RepaymentReceivedEvent.InputTuple, RepaymentReceivedEvent.OutputTuple, RepaymentReceivedEvent.OutputObject>;
      RepaymentReceived: TypedContractEvent<RepaymentReceivedEvent.InputTuple, RepaymentReceivedEvent.OutputTuple, RepaymentReceivedEvent.OutputObject>;
    

      'SpendExecuted(address,uint256,bytes32)': TypedContractEvent<SpendExecutedEvent.InputTuple, SpendExecutedEvent.OutputTuple, SpendExecutedEvent.OutputObject>;
      SpendExecuted: TypedContractEvent<SpendExecutedEvent.InputTuple, SpendExecutedEvent.OutputTuple, SpendExecutedEvent.OutputObject>;
    
    };
  }